name: ChromeMerge Script

on:
  push:
    branches:
      - main  # 替换为你的默认分支
  schedule:
    - cron: '0 0,8,18 * * *'  # 每6h一次
  workflow_dispatch:  # 触发手动事件
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # 替换为你的 Python 版本

      - name: Install dependencies
        run: cd ChromeGo_Merge && pip install -r requirements.txt

      - name: Run merge script
        run: cd ChromeGo_Merge && python meta_merge.py  # 替换为你的 merge.py 脚本名称

      - name: Run shadowrocket merge script
        run: cd ChromeGo_Merge && python merge.py  # 替换为你的 merge.py 脚本名称
        
      # BUG: lgf4591/cloudflare-pages-vpn.git denied to github-actions[bot]
      # - name: Commit Changes
      #   run: |
      #     git config core.ignorecase false
      #     git config --local user.email "lgf4591@outlook.com"
      #     git config --local user.name "lgf4591"
      #     git add .
      #     git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
      #     git push
